### ISSUE TITLE
Styles in ThemeTogle

### ISSUE THREAD

**Issue by DarkGames26** [alex4401/mediawiki-extensions-ThemeToggle#17]
Hi, I would like to report something about the styles of this extension, it is something small but I could notice. In the button to change theme, whether you have only 2 themes or several, the cursor does not change, it seems to me that you should apply a `cursor: pointer` to the button styles.

I would also like to suggest that the pseudo-class `:hover` should have some color change.

**Comment by alex4401** [comment]
As far as I'm aware, both are already the case.

- Mouse not over: ![image](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/33527044/beffce3c-7ce6-4aa6-ad21-ac0eb1cb76c0)
- Mouse over the theme list (dotted outline due to clicking): ![image](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/33527044/c77df122-53ef-4c35-97e5-ce43b79c1808)
- Mouse over a theme: ![image](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/33527044/27bd3c00-ddf4-42c3-9ec5-cbbcd1c9755d)

Colour and cursor change correctly under :hover.

I would guess this is potentially a wiki CSS issue? I would assume that if your CSS is based on Terraria Wiki's, it likely contains visual changes to the themes dropdown that might switch things up.

**Comment by DarkGames26** [comment]
Hi, I should have been more specific, when there are multiple themes it seems to work correctly, but when there are only two themes configured, I also noticed that the sun looks smaller for some reason. I attach screenshot from the support wiki they don't have any style that can affect that function

Sorry for the picture, I couldn't take a screenshot and get the cursor to show


![cursor](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/88873973/9d3c30d1-6f63-441f-8b2f-4ae46c7c37ab)
![image](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/88873973/cc794f75-00a9-4ed4-aaf3-e17dbb423ba4)

**Comment by alex4401** [comment]
Oh, the icon switcher. Yup, can add that.

**Comment by alex4401** [comment]
- Normal: 
![image](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/33527044/257f8e97-787c-4808-9015-e1885b3c73e1)
- Hovered:
![image](https://github.com/alex4401/mediawiki-extensions-ThemeToggle/assets/33527044/c290a33f-8fd1-4242-a161-b088e009751e)

**Comment by DarkGames26** [comment]
It looks very nice, but I would add a 0.3s transition

**Comment by alex4401** [comment]
Agreed.

**Comment by alex4401** [comment]
I'll make a formal ThemeToggle release with these changes and ask wiki.gg to update their install whenever DataMaps v0.16.12 is ready (hopefully either by the end of this week or sometime during next).

**Comment by alex4401** [comment]
Deployment requested.
